---
- hosts: webservers
  become: yes
  connection: ssh

  tasks: 
    - name: installing packages
      yum:
        name: ['git','which','mysql','wget','docker','tree','httpd']
        state: installed
